services:
  db:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alshnqq
      POSTGRES_DB: mydatabase
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  
volumes:
  pgdata: