version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alshnqq
      POSTGRES_DB: mydatabase
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"